version: '3.8'

services:
  solr:
    image: solr:latest
    container_name: solr-server
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - reddit_core

volumes:
  solr_data:
